import { Navigation, Autoplay } from 'swiper';
import { Swiper, SwiperSlide } from 'swiper/react';
import ProductCard from '../../productCard/productCard';
import 'swiper/css/bundle';
import './productSlider.scss';

export const ProductSlider = () => {
  return (
    <div className="product__wrapper">
      <Swiper
        className="product__swiper"
        modules={[Navigation, Autoplay]}
        spaceBetween={16}
        slidesPerView={4}
        navigation
      >
        <SwiperSlide>
          <ProductCard
            id="1"
            imgURL="#"
            price={0}
            screen="2"
            oldPrice={0}
            capacity="22"
            ram="4"
            title="Hello"
          />
        </SwiperSlide>
        <SwiperSlide>
          <ProductCard
            id="1"
            imgURL="#"
            price={0}
            screen="2"
            oldPrice={0}
            capacity="22"
            ram="4"
            title="Hello"
          />
        </SwiperSlide>
        <SwiperSlide>
          <ProductCard
            id="1"
            imgURL="#"
            price={0}
            screen="2"
            oldPrice={0}
            capacity="22"
            ram="4"
            title="Hello"
          />
        </SwiperSlide>
        <SwiperSlide>
          <ProductCard
            id="1"
            imgURL="#"
            price={0}
            screen="2"
            oldPrice={0}
            capacity="22"
            ram="4"
            title="Hello"
          />
        </SwiperSlide>
        <SwiperSlide>
          <ProductCard
            id="1"
            imgURL="#"
            price={0}
            screen="2"
            oldPrice={0}
            capacity="22"
            ram="4"
            title="Hello"
          />
        </SwiperSlide>
        <SwiperSlide>
          <ProductCard
            id="1"
            imgURL="#"
            price={0}
            screen="2"
            oldPrice={0}
            capacity="22"
            ram="4"
            title="Hello"
          />
        </SwiperSlide>
        <SwiperSlide>
          <ProductCard
            id="1"
            imgURL="#"
            price={0}
            screen="2"
            oldPrice={0}
            capacity="22"
            ram="4"
            title="Hello"
          />
        </SwiperSlide>
        <SwiperSlide>
          <ProductCard
            id="1"
            imgURL="#"
            price={0}
            screen="2"
            oldPrice={0}
            capacity="22"
            ram="4"
            title="Hello"
          />
        </SwiperSlide>
      </Swiper>
    </div>
  );
};
